CREATE TABLE [dbo].[Employee]
(
	 [Id] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	 [VacationId] UNIQUEIDENTIFIER NULL CONSTRAINT [FK_dbo_Employee_dbo_Vacation] FOREIGN KEY REFERENCES [dbo].[Vacation] ([Id]) ON DELETE SET NULL,
	 [Email] NVARCHAR(128) UNIQUE NOT NULL,
	 [Name] NVARCHAR(128) NOT NULL,
	 [Surname] NVARCHAR(128) NOT NULL
)
